version: '3.8'

services:

  stylish:
      build: 
        context: ./Backend
        dockerfile: Dockerfile
      container_name: stylish_container
      env_file:
        - .env
      networks:
        - stylish_network

  stylish_frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: stylish_frontend_container
      env_file:
        - .env
      environment:
        - NODE_OPTIONS=--max-old-space-size=4096
      networks:
        - stylish_network

  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stylish_network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  #本機對應容器
      - ./private/mergedCert.crt:/etc/ssl/mergedCert.crt
      - ./private/private.key:/etc/ssl/private.key
    networks:
      - stylish_network
    depends_on:
      - stylish


networks:
  stylish_network:   
