version: "3.8"

services:
  stylish:
    image: yingyinglininin/stylish-pro-backend:latest
    container_name: stylish_container
    env_file:
      - .env
    networks:
      - stylish_network

  stylish_frontend:
    image: yingyinglininin/stylish-pro-frontend:latest
    container_name: stylish_frontend_container
    env_file:
      - .env
    networks:
      - stylish_network

  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stylish_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1234
    networks:
      - stylish_network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf #本機對應容器
      - ./private/mergedCert.crt:/etc/ssl/mergedCert.crt
      - ./private/private.key:/etc/ssl/private.key
    networks:
      - stylish_network
    depends_on:
      - stylish

networks:
  stylish_network: